### PR TITLE
De serialize helper vector

### PR DESCRIPTION
**Pull request by thomas-lemaire**
This PR changes the behavior of helper::vector to make it closer to svector
- helper::vector can parse space separated values **and** [,] separated values
- helper::vector now serialize into [,] separated string
- helper::Vec<Type> can also parse space separated values **and** [,] separated values

As a consequence the serialization/deserialization on the python side (SofaPython plugin) is updated accordingly. Now the repr() of a python object is used to serialize it into a string in the Node.createObject() method if it is not a string already.

Later on, code can be cleaned-up:
- no more cat/concat/listToStr() calls needed in python code
- no more helper::svector needed in c++ code

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by thomas-lemaire** [comment]
Better to do a "squash and merge"

**Comment by maxime-tournier** [comment]
Nope, keep individual commits please: it's much easier to merge in case of conflicts.

**Comment by thomas-lemaire** [comment]
mmm the "squash and merge" is the policy agreed with the sofa consortium team, much cleanerand understandable history, prevent from having a "plat de spaghettis"

**Comment by maxime-tournier** [comment]
Squashing is nice for a release branch, but for a dev branch this should be avoided.

When squashing, you explicitly prevent git from merging automatically later potential conflicts by finding common ancestors, for instance when two PR touch the same files. 

Also, you're going to have *fun* times tracking down regressions when `git bisect` points at your squashed commit. 

So... at your own risks ;-)

**Comment by thomas-lemaire** [comment]
some discussion went on at:
- https://github.com/sofa-framework/sofa/pull/332
- https://github.com/sofa-framework/sofa/pull/330

**Pull request merged**
